[2023-06-24T09:04:25.185+0700] {processor.py:157} INFO - Started process (PID=1569) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:04:25.186+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T09:04:25.186+0700] {logging_mixin.py:149} INFO - [2023-06-24T09:04:25.186+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:04:25.509+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:04:25.603+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T09:09:27.841+0700] {processor.py:157} INFO - Started process (PID=1666) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:09:27.842+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T09:09:27.842+0700] {logging_mixin.py:149} INFO - [2023-06-24T09:09:27.842+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:09:28.167+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:09:28.317+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T09:10:04.200+0700] {processor.py:157} INFO - Started process (PID=1690) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:10:04.201+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T09:10:04.201+0700] {logging_mixin.py:149} INFO - [2023-06-24T09:10:04.201+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:10:04.503+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:10:04.568+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T09:30:47.255+0700] {processor.py:157} INFO - Started process (PID=1882) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:30:47.255+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T09:30:47.256+0700] {logging_mixin.py:149} INFO - [2023-06-24T09:30:47.256+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:30:47.553+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:30:47.629+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T09:42:42.302+0700] {processor.py:157} INFO - Started process (PID=2002) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:42:42.303+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T09:42:42.303+0700] {logging_mixin.py:149} INFO - [2023-06-24T09:42:42.303+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:42:42.603+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T09:42:42.676+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T10:35:55.025+0700] {processor.py:157} INFO - Started process (PID=2432) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:35:55.025+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T10:35:55.026+0700] {logging_mixin.py:149} INFO - [2023-06-24T10:35:55.025+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:35:55.325+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:35:55.397+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T10:37:52.180+0700] {processor.py:157} INFO - Started process (PID=2467) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:37:52.181+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T10:37:52.181+0700] {logging_mixin.py:149} INFO - [2023-06-24T10:37:52.181+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:37:52.487+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:37:52.559+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T10:39:21.188+0700] {processor.py:157} INFO - Started process (PID=2508) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:39:21.188+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T10:39:21.188+0700] {logging_mixin.py:149} INFO - [2023-06-24T10:39:21.188+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:39:21.497+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:39:21.563+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T10:41:15.653+0700] {processor.py:157} INFO - Started process (PID=2575) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:41:15.654+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T10:41:15.654+0700] {logging_mixin.py:149} INFO - [2023-06-24T10:41:15.654+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:41:15.967+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:41:16.037+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T10:52:59.123+0700] {processor.py:157} INFO - Started process (PID=2659) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:52:59.123+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T10:52:59.124+0700] {logging_mixin.py:149} INFO - [2023-06-24T10:52:59.124+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:52:59.439+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:52:59.516+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T10:59:44.119+0700] {processor.py:157} INFO - Started process (PID=2744) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:59:44.120+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T10:59:44.120+0700] {logging_mixin.py:149} INFO - [2023-06-24T10:59:44.120+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:59:44.432+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T10:59:44.503+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T11:01:50.975+0700] {processor.py:157} INFO - Started process (PID=2780) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T11:01:50.976+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T11:01:50.976+0700] {logging_mixin.py:149} INFO - [2023-06-24T11:01:50.976+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T11:01:51.286+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T11:01:51.359+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
[2023-06-24T11:03:32.598+0700] {processor.py:157} INFO - Started process (PID=2815) to work on /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T11:03:32.599+0700] {processor.py:826} INFO - Processing file /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py for tasks to queue
[2023-06-24T11:03:32.599+0700] {logging_mixin.py:149} INFO - [2023-06-24T11:03:32.599+0700] {dagbag.py:541} INFO - Filling up the DagBag from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T11:03:32.915+0700] {processor.py:838} WARNING - No viable dags retrieved from /Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py
[2023-06-24T11:03:32.986+0700] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 839, in process_file
    DagFileProcessor.update_import_errors(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.query(errors.ImportError).filter(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in query
    return self._query_cls(entities, self, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 180, in __init__
    self._set_entities(entities)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
    self._raw_columns = [
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
    coercions.expect(
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 186, in expect
    insp._post_inspect
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2199, in _post_inspect
    self._check_configure()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3521, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/orm/events.py", line 760, in wrap
    fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/models/__init__.py", line 67, in import_all_models
    import airflow.www.fab_security.sqla.models
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/airflow/www/fab_security/sqla/models.py", line 86, in <module>
    assoc_permission_role = Table(
  File "<string>", line 2, in __new__
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/IntelTri/WorkPlace/Aptech/Project-sem2/project-sem02/air_flows/myenv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'ab_permission_view_role' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
